#!/bin/bash

###############################################
# script for performing crest runs at FF
# and GFN2 level including clustering in order
# to get prototypical lowest lying structures
# for a subsequent CENSO run. The primary purpose 
# is NOT to get a complete ensemble but one that
# includes the globally lowest and many other
# low-lying (at DFT level) with high probability
# 10 crest runs are conducted:
# FF(neutral,v4), FF(+/-scaled disp), FF(+/-(1,2)charge)
# GFN2(neutral,v3)
# a quick version (-q) reduces the number of crest
# runs and their computational demand
# PP & SG, 7/20-1/21
###############################################

echo '                                                              '
echo '          ===================================================='
echo '          == crest_combi V 1.01, SG/PP Jan 2021, MCTC UBonn =='
echo '          ===================================================='

#defaults
solv=gas         # solvent name
ewin="8.0"       # energy window, do not take < 8 for larger drugs
gbsa='-alpb '    # solvation model
mode="ff"        # FF+GFN2(-screen)

# settings for full, non-quick default mode, change by -q 
listd="0.0 0.5 1.5 2.0" # artificial dispersion
listc="1 2 -1 -2"       #    "       ES
 xtff="x1.0"            # neutral run time
xtffm="x2.0"            # artifical "  "
nclust=500              # of clusters in itermediate steps
vfirst="-v4"            # algo for first neutral run
nmr=""                  # create anmr_nucinfo and anmr_rotamer in first FF(v4) run

threads=$OMP_NUM_THREADS  # set OMP threads (equivalent to using the -T option of crest)

argcheck=y
optstr=$@
while [ "$argcheck" = "y" ]; do
   if [ -n "$1" ]; then
      case $1 in
      "-q"    )           listd="0.5 1.5"; listc="1 -1"; xtffm="x0.5"; vfirst="-v3"; mode=ff; nclust=400 ;;
      "-s"    ) shift;    solv=$1 ;;
      "-solvent" ) shift; solv=$1 ;;
      "-g"    ) shift;    solv=$1 ;;
      "-ewin" ) shift;    ewin=$1 ;;
      "-ffonly" )         mode=ff ;;
      "-T" ) shift;       threads=$1 ;;
      "-threads" ) shift; threads=$1 ;;
      "-nmr" ) shift;     nmr="-nmr" ;;
      esac
      shift
   else
      argcheck=n
   fi  
done
ewin2=$(echo "scale=10; ($ewin+4)" | bc -l | gawk '{print $1}') # ewin for intermediate FF run re-ranking with GFN2
ewin3=$(echo "scale=10; ($ewin-2)" | bc -l | gawk '{print $1}') # ewin for last GFN2 search (if mode="")

#########################
#search on FF level
#########################
# neutral
rm -f gfnff_topo
echo 'CREST 1 (FF,"$vfirst")...' 
if [ "$nmr" == "-nmr" ]; then
    echo 'Generating anmr_nucinfo and anmr_rotamers files for possible subsequent NMR calculation'
    crest coord $gbsa $solv -gfnff $vfirst -cluster $nclust -ewin $ewin -norotmd -nocross -mdlen $xtff -T $threads $nmr
else
    crest coord $gbsa $solv -gfnff $vfirst -cluster $nclust -ewin $ewin -norotmd -nocross -mdlen $xtff -T $threads
fi
mv crest_conformers.xyz crest_tmp.xyz
mv crest_best.xyz best_gfnff.xyz
cat crest_clustered.xyz > search_gfnff.xyz

# artificial 1
for dscal in $listd          
do
echo 'CREST (FF+/-disp)...' $dscal
rm -f gfnff_topo
# search with scaled dispersion interaction via the "-dispscal" command
crest best_gfnff.xyz -gfnff -cluster $nclust -ewin $ewin -dispscal $dscal -norotmd -norestart -nocross -mdlen $xtffm -T $threads
cat crest_clustered.xyz >> search_gfnff.xyz
done

chrg=0
if test -f .CHRG; then
 chrg=`cat .CHRG`
fi

# artificial 2
for c in $listc   
do
chrgmod=$(echo "scale=10; ($chrg+$c)" | bc -l | gawk '{print $1}')
echo 'CREST (FF+/-charge)...' $chrgmod
rm -f gfnff_topo
echo $chrgmod > .CHRG
# search with modified molecular charge +/-{1,2}
crest best_gfnff.xyz -gfnff -cluster $nclust -ewin $ewin -norotmd -norestart -nocross -mdlen $xtffm -T $threads
cat crest_clustered.xyz >> search_gfnff.xyz
done
echo $chrg > .CHRG

# GFN2 opt
echo 'CREST screen (GFN2)...' 
cp search_gfnff.xyz search_gfnff_save.xyz
rm -f gfnff_topo
#1. energy re-rank (at FF level) because of +/-disp/ES structures (output: crest_ensemble.xyz)
crest -mdopt search_gfnff.xyz $gbsa $solv -opt crude -gfnff -ewin $ewin2 -T $threads  
#2. Sorting of the optimized ensemble (output: overwritten crest_ensemble.xyz)
crest -cregen crest_ensemble.xyz -ewin $ewin -ethr 0.1 und -rthr 0.2 -bthr 0.03 -T $threads
#3. GFN2 full opt (output: overwritten crest_ensemble.xyz)
crest $gbsa $solv -screen crest_ensemble.xyz -opt vtight -gfn2 -ewin $ewin -T $threads
#4. PCA/k-Means clustering of final ensemble (output: crest_clustered.xyz)
crest -for crest_ensemble.xyz -cluster $nclust -ewin $ewin -T $threads
mv crest_clustered.xyz search_gfnff.xyz
mv crest_best.xyz        best_gfnff.xyz

#########################
# FF only part ends here
#########################
if [ "$mode" = "ff" ]; then           
   crest -for search_gfnff.xyz -cluster tightincr -ewin $ewin -T $threads 
   mv crest_clustered.xyz crest_combi.xyz
else
###############################################################
#search on GFN2 level starting with best at GFN2 opt from FF SE  
###############################################################
   echo 'CREST 8 (GFN2) ...' $level2
   crest best_gfnff.xyz $gbsa $solv -gfn2 -ewin $ewin3 -norotmd -nocross -mdlen x1.0 -T $threads
   crest -for crest_conformers.xyz -cluster $nclust -T $threads
   mv crest_best.xyz        best_gfn2.xyz
   mv crest_clustered.xyz search_gfn2.xyz
   
   # merge FF/TB  
   cat search_gfnff.xyz   > final.xyz
   cat search_gfn2.xyz   >> final.xyz
   echo 'CREST final cregen ...'
   crest -cregen final.xyz -ewin $ewin -T $threads
   crest -for crest_ensemble.xyz -cluster $nclust -ewin $ewin -T $threads
   crest -for crest_clustered.xyz -cluster tightincr -ewin $ewin -T $threads
   cp crest_clustered.xyz crest_combi.xyz
fi

# the workflow provides a final ensemble called "crest_combi.xyz" for further processing
                                    

